// src/editor/Preview.tsx
import type { RenderedSvgPage } from "@vedivad/typst-web-service";
import {
  TbOutlineArrowAutofitHeight,
  TbOutlineArrowAutofitWidth,
  TbOutlineZoomIn,
  TbOutlineZoomOut,
} from "solid-icons/tb";
import { createMemo, createSignal, Index, onCleanup, onMount } from "solid-js";

import { Button } from "../components/ui/button";
import { useTheme } from "../lib/ThemeContext";

interface Props {
  pages: RenderedSvgPage[];
}

const BASE_WIDTH_PX = 700;
const ZOOM_STEP = 1.1;
const ZOOM_MIN = 0.25;
const ZOOM_MAX = 4;
const SCROLLER_PADDING_PX = 24;

const clampZoom = (z: number) => Math.min(ZOOM_MAX, Math.max(ZOOM_MIN, z));

export default function Preview(props: Props) {
  const { theme } = useTheme();
  const [zoom, setZoom] = createSignal(1);
  const [panning, setPanning] = createSignal(false);

  // Hold the last non-empty pages so the preview keeps showing the previous output
  // (faded) while a recompile is in flight.
  const displayPages = createMemo<RenderedSvgPage[]>(
    (prev) => (props.pages.length > 0 ? props.pages : prev),
    []
  );

  let scroller: HTMLDivElement | undefined;
  let panOrigin: { x: number; y: number; scrollLeft: number; scrollTop: number } | null = null;

  const zoomAt = (newZoom: number, anchorClientX?: number, anchorClientY?: number) => {
    if (!scroller) {
      return;
    }
    const next = clampZoom(newZoom);
    const prev = zoom();
    if (next === prev) {
      return;
    }
    const ratio = next / prev;
    const rect = scroller.getBoundingClientRect();
    const ax = (anchorClientX ?? rect.left + rect.width / 2) - rect.left;
    const ay = (anchorClientY ?? rect.top + rect.height / 2) - rect.top;
    const sl = scroller.scrollLeft;
    const st = scroller.scrollTop;
    setZoom(next);
    requestAnimationFrame(() => {
      if (!scroller) {
        return;
      }
      scroller.scrollLeft = (sl + ax) * ratio - ax;
      scroller.scrollTop = (st + ay) * ratio - ay;
    });
  };

  const onWheel = (e: WheelEvent) => {
    if (!e.ctrlKey) {
      return;
    }
    e.preventDefault();
    zoomAt(e.deltaY > 0 ? zoom() / ZOOM_STEP : zoom() * ZOOM_STEP, e.clientX, e.clientY);
  };

  const fitWidth = () => {
    if (!scroller) {
      return;
    }
    zoomAt(clampZoom((scroller.clientWidth - SCROLLER_PADDING_PX) / BASE_WIDTH_PX));
  };

  const fitHeight = () => {
    if (!scroller) {
      return;
    }
    const firstPage = displayPages()[0];
    if (!firstPage) {
      return;
    }
    const pageHeightPx = (firstPage.height / firstPage.width) * BASE_WIDTH_PX;
    zoomAt(clampZoom((scroller.clientHeight - SCROLLER_PADDING_PX) / pageHeightPx));
  };

  // The rendered SVG calls this as a global onclick handler for source links —
  // the rendered output emits `onclick="handleTypstLocation(...)"` inline, so a
  // delegated listener wouldn't see it.
  function handleTypstLocation(_el: unknown, page: number, _x: number, y: number) {
    if (!scroller) {
      return;
    }
    const pageEls = scroller.querySelectorAll<HTMLElement>(".typst-page");
    const target = pageEls[page - 1];
    if (!target) {
      return;
    }
    const svgEl = target.querySelector("svg");
    const targetRect = target.getBoundingClientRect();
    const scrollerRect = scroller.getBoundingClientRect();
    const scale = svgEl ? targetRect.height / svgEl.viewBox.baseVal.height : 1;
    scroller.scrollTo({
      top: scroller.scrollTop + (targetRect.top - scrollerRect.top) + y * scale - 40,
      behavior: "smooth",
    });
  }

  onMount(() => {
    (globalThis as Record<string, unknown>)["handleTypstLocation"] = handleTypstLocation;
    requestAnimationFrame(() => {
      if (!scroller) {
        return;
      }
      const fit = (scroller.clientWidth - SCROLLER_PADDING_PX) / BASE_WIDTH_PX;
      if (fit < 1) {
        setZoom(clampZoom(fit));
      }
    });
  });

  onCleanup(() => {
    const slot = globalThis as Record<string, unknown>;
    if (slot["handleTypstLocation"] === handleTypstLocation) {
      delete slot["handleTypstLocation"];
    }
  });

  const onPointerDown = (e: PointerEvent) => {
    if (e.button !== 0 || !scroller) {
      return;
    }
    e.preventDefault();
    scroller.setPointerCapture(e.pointerId);
    scroller.focus({ preventScroll: true });
    panOrigin = {
      x: e.clientX,
      y: e.clientY,
      scrollLeft: scroller.scrollLeft,
      scrollTop: scroller.scrollTop,
    };
    setPanning(true);
  };

  const onPointerMove = (e: PointerEvent) => {
    if (!panOrigin || !scroller) {
      return;
    }
    scroller.scrollLeft = panOrigin.scrollLeft - (e.clientX - panOrigin.x);
    scroller.scrollTop = panOrigin.scrollTop - (e.clientY - panOrigin.y);
  };

  const onPointerUp = (e: PointerEvent) => {
    if (scroller?.hasPointerCapture(e.pointerId)) {
      scroller.releasePointerCapture(e.pointerId);
    }
    panOrigin = null;
    setPanning(false);
  };

  return (
    <div class="flex h-full w-full flex-col overflow-hidden">
      <div class="border-border/60 bg-background flex shrink-0 items-center gap-1 border-b px-2 py-1">
        <Button
          variant="ghost"
          size="icon-sm"
          title="Zoom out"
          aria-label="Zoom out"
          onClick={() => {
            zoomAt(zoom() / ZOOM_STEP);
          }}
        >
          <TbOutlineZoomOut />
        </Button>
        <Button
          variant="ghost"
          size="sm"
          class="w-14 font-mono tabular-nums"
          title="Reset zoom"
          aria-label="Reset zoom"
          onClick={() => {
            zoomAt(1);
          }}
        >
          {Math.round(zoom() * 100)}%
        </Button>
        <Button
          variant="ghost"
          size="icon-sm"
          title="Zoom in"
          aria-label="Zoom in"
          onClick={() => {
            zoomAt(zoom() * ZOOM_STEP);
          }}
        >
          <TbOutlineZoomIn />
        </Button>
        <Button
          variant="ghost"
          size="icon-sm"
          title="Fit height"
          aria-label="Fit height"
          onClick={() => {
            fitHeight();
          }}
        >
          <TbOutlineArrowAutofitHeight />
        </Button>
        <Button
          variant="ghost"
          size="icon-sm"
          title="Fit width"
          aria-label="Fit width"
          onClick={() => {
            fitWidth();
          }}
        >
          <TbOutlineArrowAutofitWidth />
        </Button>
      </div>

      <div
        ref={(el) => {
          scroller = el;
        }}
        tabindex={-1}
        class="bg-muted/40 min-h-0 flex-1 cursor-grab overflow-auto p-3 outline-none"
        classList={{ "!cursor-grabbing select-none": panning() }}
        onWheel={onWheel}
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={onPointerUp}
        onPointerCancel={onPointerUp}
      >
        <div
          class="mx-auto flex flex-col items-center gap-6"
          style={{
            width: `${String(zoom() * BASE_WIDTH_PX)}px`,
            ...(theme() === "dark" ? { filter: "invert(0.85) hue-rotate(180deg)" } : {}),
          }}
        >
          <Index each={displayPages()}>
            {(page) => (
              <div
                class="w-full bg-white shadow-md ring-1 ring-black/10 [&_svg]:block [&_svg]:h-auto [&_svg]:w-full"
                classList={{ "opacity-50": props.pages.length === 0 }}
                innerHTML={page().svg}
              />
            )}
          </Index>
        </div>
      </div>
    </div>
  );
}

// src/editor/Preview.svelte
<script lang="ts">
  import { splitPages } from "./svgUtils";

  interface Props {
    svg?: string;
  }

  let { svg }: Props = $props();

  const pages = $derived(svg ? splitPages(svg) : []);

  let prevPages = $state<string[]>([]);
  $effect(() => {
    if (pages.length > 0) prevPages = pages;
  });

  const displayPages = $derived(pages.length > 0 ? pages : prevPages);
  const loading = $derived(pages.length === 0);

  let previewEl: HTMLDivElement;
  let dropdownWrapEl: HTMLDivElement;

  const ZOOM_STEP = 0.1;
  const MIN_ZOOM = 0.25;
  const MAX_ZOOM = 3.0;
  // Sum of left + right (or top + bottom) padding on .preview, used for fit calculations.
  const PREVIEW_PADDING = 32;

  let zoom = $state(1.0);
  let showDropdown = $state(false);

  function setZoom(value: number) {
    zoom = Math.min(MAX_ZOOM, Math.max(MIN_ZOOM, Math.round(value * 10) / 10));
    showDropdown = false;
  }

  function zoomIn() {
    setZoom(zoom + ZOOM_STEP);
  }
  function zoomOut() {
    setZoom(zoom - ZOOM_STEP);
  }

  function fitDimension(dim: "width" | "height") {
    const svgEl = previewEl.querySelector<SVGSVGElement>(".page svg");
    if (!svgEl) return;
    const rect = svgEl.getBoundingClientRect();
    const natural = (dim === "width" ? rect.width : rect.height) / zoom;
    const available =
      (dim === "width" ? previewEl.clientWidth : previewEl.clientHeight) - PREVIEW_PADDING;
    setZoom(available / natural);
  }

  function handleWindowClick(e: MouseEvent) {
    if (showDropdown && !dropdownWrapEl.contains(e.target as Node)) {
      showDropdown = false;
    }
  }

  // The typst renderer injects onclick="handleTypstLocation(el, page, x, y)" into SVG links.
  // Scroll the preview to the target page and y-position.
  function handleTypstLocation(_el: unknown, page: number, _x: number, y: number) {
    const pageEls = previewEl.querySelectorAll<HTMLElement>(".page");
    const target = pageEls[page - 1] as HTMLElement | undefined;
    if (!target) return;
    const svgEl = target.querySelector("svg");
    const scale = svgEl ? target.clientHeight / svgEl.viewBox.baseVal.height : 1;
    previewEl.scrollTo({
      top: target.offsetTop - previewEl.offsetTop + y * scale - 40,
      behavior: "smooth",
    });
  }

  if (typeof window !== "undefined") {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-member-access
    (window as any).handleTypstLocation = handleTypstLocation;
  }
</script>

<svelte:window onclick={handleWindowClick} />

<div class="preview-wrapper">
  <div class="preview-toolbar">
    <button class="zoom-btn" onclick={zoomIn} disabled={zoom >= MAX_ZOOM}>+</button>

    <div class="zoom-label-wrap" bind:this={dropdownWrapEl}>
      <button class="zoom-label" onclick={() => (showDropdown = !showDropdown)}>
        {Math.round(zoom * 100)}%
      </button>

      {#if showDropdown}
        <div class="zoom-dropdown">
          <button onclick={() => { fitDimension("width"); }}>Fit Width</button>
          <button onclick={() => { fitDimension("height"); }}>Fit Height</button>
          <hr />
          <button onclick={() => { setZoom(0.5); }}>50%</button>
          <button onclick={() => { setZoom(0.75); }}>75%</button>
          <button onclick={() => { setZoom(1.0); }}>100%</button>
          <button onclick={() => { setZoom(2.0); }}>200%</button>
        </div>
      {/if}
    </div>

    <button class="zoom-btn" onclick={zoomOut} disabled={zoom <= MIN_ZOOM}>−</button>
  </div>

  <div class="preview" bind:this={previewEl}>
    <div class="pages" style="zoom: {zoom}">
      {#each displayPages as page, i (i)}
        <div class="page" class:loading>
          <!-- eslint-disable-next-line svelte/no-at-html-tags -->
          {@html page}
        </div>
      {/each}
    </div>
  </div>
</div>

<style>
  .preview-wrapper {
    display: flex;
    flex-direction: column;
    height: 100%;
    overflow: hidden;
  }

  .preview-toolbar {
    display: flex;
    align-items: center;
    gap: 0.25rem;
    padding: 0.35rem 0.5rem;
    background: var(--color-surface);
    border-bottom: 1px solid var(--color-border);
    flex-shrink: 0;
  }

  .zoom-btn {
    font-size: 0.85rem;
    width: 1.4rem;
    height: 1.4rem;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 1px solid var(--color-border);
    border-radius: 4px;
    background: var(--color-bg);
    color: var(--color-text);
    cursor: pointer;
    line-height: 1;
    padding: 0;
  }

  .zoom-btn:hover:not(:disabled) {
    background: var(--color-surface-hover);
  }

  .zoom-btn:disabled {
    opacity: 0.4;
    cursor: default;
  }

  .zoom-label-wrap {
    position: relative;
  }

  .zoom-label {
    font-size: 0.75rem;
    min-width: 3rem;
    height: 1.4rem;
    text-align: center;
    color: var(--color-text);
    border: 1px solid var(--color-border);
    border-radius: 4px;
    background: var(--color-bg);
    cursor: pointer;
    padding: 0 0.25rem;
  }

  .zoom-label:hover {
    background: var(--color-surface-hover);
  }

  .zoom-dropdown {
    position: absolute;
    top: calc(100% + 4px);
    left: 50%;
    transform: translateX(-50%);
    background: var(--color-bg);
    border: 1px solid var(--color-border);
    border-radius: 6px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
    display: flex;
    flex-direction: column;
    min-width: 7rem;
    z-index: 100;
    overflow: hidden;
  }

  .zoom-dropdown button {
    font-size: 0.75rem;
    padding: 0.35rem 0.75rem;
    text-align: left;
    background: none;
    border: none;
    color: var(--color-text);
    cursor: pointer;
    white-space: nowrap;
  }

  .zoom-dropdown button:hover {
    background: var(--color-surface-hover);
  }

  .zoom-dropdown hr {
    margin: 0.2rem 0;
    border: none;
    border-top: 1px solid var(--color-border);
  }

  .preview {
    flex: 1;
    overflow: auto;
    background: var(--color-surface, #f0f0f0);
    padding: 1rem;
  }

  .pages {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    transform-origin: top center;
  }

  .page {
    background: white;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
    width: fit-content;
    flex-shrink: 0;
  }

  .page.loading :global(svg) {
    visibility: hidden;
  }

  .page :global(svg) {
    display: block;
    max-width: none;
  }
</style>
