// src/TourLayout.tsx
import { Show } from "solid-js";

import LessonContent from "./components/LessonContent";
import ResizeHandle from "./components/ResizeHandle";
import type { Chapter } from "./content/types";
import Workspace from "./editor/Workspace";

interface Props {
  locale: string;
  chapters: Chapter[];
  currentIndex: number;
  currentKey: string;
  contentFraction: number;
  resetGeneration: number;
  contentBlurred?: boolean;
  onContentFractionChange: (f: number) => void;
}

export default function TourLayout(props: Props) {
  const currentChapter = () => props.chapters.at(props.currentIndex);

  return (
    <div
      class="flex min-h-0 flex-1"
      style={{ "max-width": "1600px", width: "100%", margin: "0 auto" }}
    >
      <div
        class="border-border flex min-w-0 flex-col overflow-hidden border-r"
        style={{ flex: props.contentFraction }}
      >
        <main
          class="flex-1 overflow-y-auto px-12 py-8 transition-[filter] duration-200"
          classList={{ "blur-sm": props.contentBlurred }}
        >
          <Show when={currentChapter()}>
            {(chapter) => (
              <LessonContent chapter={chapter()} index={props.currentIndex} locale={props.locale} />
            )}
          </Show>
        </main>
      </div>

      <ResizeHandle
        direction="horizontal"
        fraction={props.contentFraction}
        min={0.25}
        max={0.75}
        onChange={props.onContentFractionChange}
      />

      <div
        class="flex min-w-0 flex-col overflow-hidden"
        style={{ flex: 1 - props.contentFraction }}
      >
        <Workspace
          locale={props.locale}
          chapterKey={props.currentKey}
          resetGeneration={props.resetGeneration}
        />
      </div>
    </div>
  );
}

// src/TourLayout.svelte
<script lang="ts">
  import ResizeHandle from "./components/ResizeHandle.svelte";
  import Workspace from "./editor/Workspace.svelte";
  import LessonContent from "./components/LessonContent.svelte";
  import type { Chapter } from "./content/types";

  interface Props {
    locale: string;
    theme: "light" | "dark";
    chapters: Chapter[];
    currentIndex: number;
    currentKey: string;
    contentFraction: number;
    tocDropdownOpen: boolean;
  }

  let {
    locale,
    theme,
    chapters,
    currentIndex,
    currentKey,
    contentFraction,
    tocDropdownOpen,
  }: Props = $props();
</script>

<div class="layout">
  <div class="content-side" style="flex: {contentFraction}">
    <main class="content-panel" class:blurred={tocDropdownOpen}>
      <LessonContent chapter={chapters[currentIndex]} index={currentIndex} {locale} />
    </main>
  </div>

  <ResizeHandle
    direction="horizontal"
    fraction={contentFraction}
    onchange={(f: number) => (contentFraction = f)}
  />

  <div class="workspace-side" style="flex: {1 - contentFraction}">
    <Workspace {locale} chapterKey={currentKey} {theme} />
  </div>
</div>

<style>
  .layout {
    display: flex;
    flex: 1;
    min-height: 0;
    max-width: 1600px;
    width: 100%;
    margin: 0 auto;
  }

  .content-side,
  .workspace-side {
    display: flex;
    flex-direction: column;
    min-width: 0;
    overflow: hidden;
    border-right: 1px solid var(--color-border);
  }

  .content-panel {
    flex: 1;
    overflow-y: auto;
    padding: 2rem 3rem;
    transition: filter 0.2s ease;
  }

  .content-panel.blurred {
    filter: blur(3px);
    pointer-events: none;
    user-select: none;
  }
</style>
